### ISSUE TITLE
Still crash

### ISSUE THREAD

**Issue by terrorist96** [DVDAndroid/XposedInstaller#170]
###### Include the following:
 - Xposed Version: `87` 
 - [x] Xposed Systemless
 - Device OS version: `6.0.1`
 - Device Manufacturer: `Huawei`
 - Device Name: `Nexus 6p`
 - Material Xposed Installer version: `04/08/2017`
 
###### Reproduction Steps

1. Open app

###### Expected Result

No crash since I have the latest version with the [commit](https://github.com/DVDAndroid/XposedInstaller/commit/440100c3c333f35ff00ef53fa8e89c0115a64041) to avoid the crash.

###### Actual Result
Crash

java.lang.RuntimeException: Unable to start activity ComponentInfo{de.robv.android.xposed.installer/de.robv.android.xposed.installer.WelcomeActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5422)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
	at android.widget.ArrayAdapter.getCount(ArrayAdapter.java:337)
	at android.widget.AbsSpinner.setAdapter(AbsSpinner.java:115)
	at android.widget.Spinner.setAdapter(Spinner.java:508)
	at android.support.v7.widget.AppCompatSpinner.setAdapter(AppCompatSpinner.java:399)
	at de.robv.android.xposed.installer.installation.BaseAdvancedInstaller.onCreateView(BaseAdvancedInstaller.java:149)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2337)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3217)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3171)
	at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2352)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1442)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3217)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3171)
	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:552)
	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
	at android.app.Activity.performStart(Activity.java:6268)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
	... 10 more

**Comment by DVDAndroid** [comment]
Does the app crash when you open it a second time?

**Comment by terrorist96** [comment]
No. Half the time it doesn't crash when I open it the first time either. But if I do open it and it crashes, trying to open it again will not crash, so it's just a minor annoyance when it does happen.

**Comment by terrorist96** [comment]
I also have Magisk installed through which I have xposed installed, if that helps narrow down the issue.
