### ISSUE TITLE
NameNotFound exception - SettingsActivity

### ISSUE THREAD

**Issue by jwchips** [DVDAndroid/XposedInstaller#187]
###### Include the following:
 - Xposed Version: `88.2` 
 - [x ] Xposed Systemless
 - Device OS version: `7.1.2`
 - Device Manufacturer: `Xiaomi`
 - Device Name: `Redmi4X`
 - Material Xposed Installer version: `30/10/2017`
 
###### Reproduction Steps

1. Launch installer app
2. Switch out
3. Return to installer app

###### Expected Result
App is shown on  screen 

###### Actual Result
NameNotFound exception when trying to launch 'WelcomeActivitydvdandroid' which is 2 separate variables that are concatenated by onPreferenceChange() in SettingsActivity

`java.lang.RuntimeException: Unable to start activity ComponentInfo{de.robv.android.xposed.installer/de.robv.android.xposed.installer.WelcomeActivity}: java.lang.IllegalArgumentException: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{de.robv.android.xposed.installer/de.robv.android.xposed.installer.WelcomeActivitydvdandroid}
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2706)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4576)
	at android.app.ActivityThread.-wrap19(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1522)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6205)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: java.lang.IllegalArgumentException: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{de.robv.android.xposed.installer/de.robv.android.xposed.installer.WelcomeActivitydvdandroid}
	at android.support.v4.app.NavUtils.getParentActivityName(NavUtils.java:222)
	at android.support.v7.app.AppCompatDelegateImplV9.onCreate(AppCompatDelegateImplV9.java:155)
	at android.support.v7.app.AppCompatDelegateImplV14.onCreate(AppCompatDelegateImplV14.java:59)
	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:72)
	at de.robv.android.xposed.installer.XposedBaseActivity.onCreate(XposedBaseActivity.java:15)
	at de.robv.android.xposed.installer.WelcomeActivity.onCreate(WelcomeActivity.java:48)
	at android.app.Activity.performCreate(Activity.java:6864)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
	... 11 more
Caused by: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{de.robv.android.xposed.installer/de.robv.android.xposed.installer.WelcomeActivitydvdandroid}
	at android.app.ApplicationPackageManager.getActivityInfo(ApplicationPackageManager.java:391)
	at android.support.v4.app.NavUtils.getParentActivityName(NavUtils.java:240)
	at android.support.v4.app.NavUtils.getParentActivityName(NavUtils.java:219)
	... 19 more
`

**Comment by DVDAndroid** [comment]
Could you try this [apk](https://github.com/DVDAndroid/XposedInstaller/files/1444109/XposedInstaller_by_dvdandroid_test.zip)? (replace .zip with .apk)
