### ISSUE TITLE
Crash after searching for a module in download tab

### ISSUE THREAD

**Issue by BBPSBB** [DVDAndroid/XposedInstaller#192]
###### Include the following:
 - Xposed Version: `90.1-beta3` 
 - [x] Xposed Systemless
 - Device OS version: `8.1.0`
 - Device Manufacturer: `Xiaomi`
 - Device Name: `Mi 5s`
 - Material Xposed Installer version: `25/12/2017`
 
###### Reproduction Steps

1. navigate to download tab
2. search for something e.g. "camera"
3. tap on an item in the results e.g. "cameraNotify"

###### Expected Result
being able to view the module page.

###### Actual Result
crash after a second

###### Stack Trace

java.lang.IllegalStateException: Handling non empty state of parent class is not implemented
 at se.emilsjolander.stickylistheaders.StickyListHeadersListView.onSaveInstanceState(StickyListHeadersListView.java:1098)
 at android.view.View.dispatchSaveInstanceState(View.java:17614)
 at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3720)
 at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3726)
 at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3726)
 at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3726)
 at android.view.View.saveHierarchyState(View.java:17597)
 at android.support.v4.app.FragmentManagerImpl.saveFragmentViewState(FragmentManager.java:2859)
 at android.support.v4.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:2880)
 at android.support.v4.app.FragmentManagerImpl.saveAllState(FragmentManager.java:2933)
 at android.support.v4.app.FragmentController.saveAllState(FragmentController.java:125)
 at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:540)
 at android.support.v7.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:509)
 at de.robv.android.xposed.installer.WelcomeActivity.onSaveInstanceState(WelcomeActivity.java:224)
 at android.app.Activity.performSaveInstanceState(Activity.java:1496)
 at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1386)
 at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4721)
 at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4025)
 at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4084)
 at android.app.ActivityThread.-wrap24(Unknown Source:0)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1622)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:164)
 at android.app.ActivityThread.main(ActivityThread.java:6494)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
 at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)

**Comment by DVDAndroid** [comment]
Could you test this apk? (replace .zip with .apk)
[XposedInstaller_by_dvdandroid_test.zip](https://github.com/DVDAndroid/XposedInstaller/files/1741719/XposedInstaller_by_dvdandroid_test.zip)

**Comment by BBPSBB** [comment]
great! i can't reproduce the crash with the test version.
thanks for the fix

**Comment by DVDAndroid** [comment]
I don't know when I'll release a new update. For now use this version please
